### ISSUE TITLE
More Educational Interface

### ISSUE THREAD

**Issue by Ipstenu** [georgestephanis/application-passwords#1] opened 2016-01-14 22:58 UTC
Looking at this example from Google, there are a couple takeaways I think would help us:

![screen shot 2016-01-14 at 2 54 17 pm](https://cloud.githubusercontent.com/assets/807903/12340324/0300be18-bacf-11e5-99aa-df18deba4cdc.png)
1. By having a dropdown, we're educating users as to WHAT this will be used for. iPhone, iPad, Rest API, Jetpack ;) That will help them understand the purpose.
2. Having the [REVOKE] button on that line, always visible, is good for security. It's easier to tell someone 'Go to the profile page, scroll down to App Passwords, press REVOKE for the item you want to kill in fire.'  I think this is one location where the WP Tables interface is not right. Pretty much all we'll ever want to do is revoke access.

**Comment by georgestephanis** [comment] 2016-01-15 15:20
We could very easily stop using the WP_List_Table class and just create the table manually and run it all through JS instead of PHP.

**Comment by scarstens** [comment] 2016-01-18 23:32
Also after testing, nothing indicates that these passwords are "temporary", but they are. They are gone after page reload.

**Comment by scarstens** [comment] 2016-01-18 23:36
Maybe its too much, wouldn't know without asking the core team, but I was thinking there should be a new page under users for "Security". Between 2FA and Application passwords and regular user passwords and roles, I wouldn't mind seeing all this get moved asside the other user profile meta like "Display Name" and "Twitter Name"

![image](https://cloud.githubusercontent.com/assets/1483300/12405466/b0bc8ee4-be01-11e5-942b-45a02ecfca5c.png)

**Comment by Ipstenu** [comment] 2016-01-19 16:39
Where's the line between security and profile for 'passwords' though. I think, for **now** leaving this on the Your Profile Page is appropriate. Leave the refactoring of the profile page to another project.

**Comment by georgestephanis** [comment] 2016-01-21 18:43
So, for columns in the table, would we want then ...

Name | Created | Last Used | Last IP | Revoke Button

?

I'm tempted to ditch the WP_List_Table class and just build it purely in JS for simplicity.  Not sure if that'd be silly though.

**Comment by voldemortensen** [comment] 2016-01-21 18:50
Doing it purely in JS would leave it without a no-js fallback, no? I understand the world is moving towards JS (which has its pros and cons, especially from a security perspective), but I think its long been a core value to have a no-js fallback.

**Comment by georgestephanis** [comment] 2016-01-21 18:56
Well, some stuff has been necessary for a no-js fallback -- logging in/out, activating/deactivating plugins, switching themes -- basically the stuff that you need to be able to do to get your site working properly and resolve conflicts caused by borked JS.

As to whether or not this would need a no-js fallback, and for what aspects, I'm not quite certain.

**Comment by georgestephanis** [comment] 2016-01-27 22:00
In c0a3bfa6ab6e9df63b7acb94bac14faae3bd9496 I migrated to a new 'revoke' column and 27274f750be517fd92525ebf2119b3b219383ab6 simplified the admin screen for users not using app passwords by hiding the table entirely if it's empty.

**Comment by georgestephanis** [comment] 2016-02-19 18:41
By the way, here's a album showing the full workflow for application passwords in Google's account administration:

https://cloudup.com/cVFCCpQ2t3X

**Comment by georgestephanis** [comment] 2016-02-19 18:52
Just to confirm, GitHub's personal access tokens are actually 40 character hex strings.

So they would have 16^40 entropy, or 160 entropy.  Also p. hard to type out places.

**Comment by georgestephanis** [comment] 2017-02-12 00:34
Closing this out following prior efforts to simplify the listing.  More may come down the road if we get a designer willing to put some time in.

**Closed by georgestephanis** 2017-02-12 00:34 UTC
